# Site settings
encoding: utf-8
title: สำนักอักขระฟอนต์อยู่นี่
short_title: ฟอนต์อยู่นี่
tagline: ฟอนต์เกิดใหม่บ้างในบางเวลา ...
description: > # this means to ignore newlines until "baseurl:"
  สำนักอักขระฟอนต์อยู่นี่  มุ่งผลิตฟอนต์เสรีให้แสดงผลได้ถูกต้องและดีพอ เน้นมาตรฐานยูนิโค้ดและโอเพ่นไทป์ เพื่อให้ทุกคนมีอิสระในการใช้งาน, แจกจ่าย หรือดัดแปลงได้อย่างสบายใจ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fontuni.com" # the base hostname & protocol for your site
timezone: Asia/Bangkok

email: uni@fontuni.com
github_username: FontUni
twitter_username: FontUni
facebook_username: FontUni

# Build settings
permalink: /articles/:year-:month-:day-:title.html
markdown: kramdown

excerpt_separator: <!--more-->

# Github
github:
  owner_name: "fontuni"
  owner_url: "https://github.com/fontuni"
  repository_url: "https://github.com/fontuni/fontuni.github.io"

# Github Pages Sitemap
gems:
  - jekyll-sitemap
  - jekyll-paginate

collections:
  fonts:
    output: true
    permalink: /:path.html
    defaults:
      scope:
        path: ""
        type: font
      values:
        layout: font

exclude:
  - CNAME
  - README.md
  - "*.bak"
  - "_fonts/*/backup/*"
  - "_fonts/*/scripts/*"
  - "_fonts/*/sfd/*"
  - "_fonts/*/sources/*"
  - "_fonts/*/fonts/unhinted/*"
  - "_fonts/*/fonts/*.zip"

# reveal.js url
revealjs: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.2.0

# custom site nav
navs:
  - url: /about/
    title: แนวคิดอยู่นี่
  - url: /articles/
    title: บทความอยู่นี่
