# Site settings
encoding: utf-8
title: สำนักอักขระฟอนต์อยู่นี่
short_title: ฟอนต์อยู่นี่
tagline: ฟอนต์เกิดใหม่บ้างในบางเวลา ...
description: > # this means to ignore newlines until "baseurl:"
  สำนักอักขระฟอนต์อยู่นี่  เป็นโรงหล่อฟอนต์เสรีที่มุ่งผลิตฟอนต์ไทยให้แสดงผลได้ถูกต้องและดูไม่แย่ เน้นมาตรฐานยูนิโค้ดและโอเพ่นไทป์ เพื่อให้มนุษย์ไทยและมนุษย์โลกมีอิสระที่จะนำฟอนต์ไปใช้งาน, แจกจ่าย หรือดัดแปลงได้อย่างสบายใจ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fontuni.com" # the base hostname & protocol for your site
timezone: Asia/Bangkok

email: uni@fontuni.com
github_username: fontuni
twitter_username: fontuni
facebook_username: fontuni

# Build settings
permalink: /articles/:year-:month-:day-:title.html
markdown: kramdown
exclude: [CNAME, README.md]

# Github
github:
  owner_name: "fontuni"
  owner_url: "https://github.com/fontuni"
  repository_url: "https://github.com/fontuni/fontuni.github.io"

# Github Pages Sitemap
gems:
  - jekyll-sitemap

collections:
  boon:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
  boonbaan:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
  boonjot:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
  boontook:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
  vain:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
  f0nt:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font

exclude: [
  _boon/backup,
  _boon/scripts,
  _boon/sfd,
  _boon/sources,
  _boonbaan/backup,
  _boonbaan/scripts,
  _boonbaan/sfd,
  _boonbaan/sources,
  _boonjot/backup,
  _boonjot/scripts,
  _boonjot/sfd,
  _boonjot/sources,
  _boontook/backup,
  _boontook/scripts,
  _boontook/sfd,
  _boontook/sources,
  _vain/backup,
  _vain/scripts,
  _vain/sfd,
  _vain/sources,
  _f0nt/backup,
  _f0nt/scripts,
  _f0nt/sfd,
  _f0nt/sources 
]

# reveal.js url
revealjs: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.2.0
