# Site settings
title: สำนักอักขระฟอนต์อยู่นี่
short_title: ฟอนต์อยู่นี่
tagline: ก็ทำฟอนต์บ้างในบางเวลา ...
description: > # this means to ignore newlines until "baseurl:"
  สำนักอักขระฟอนต์อยู่นี่  เป็นโรงหล่อฟอนต์เสรีที่มุ่งผลิตฟอนต์ไทยให้แสดงผลได้ถูกต้องและดูไม่แย่ เน้นมาตรฐานยูนิโค้ดและโอเพ่นไทป์ เพื่อให้มนุษย์ไทยและมนุษย์โลกมีอิสระที่จะนำฟอนต์ไปใช้งาน, แจกจ่าย หรือดัดแปลงได้อย่างสบายใจ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fontuni.com" # the base hostname & protocol for your site
email: uni@fontuni.com
twitter_username: fontuni
github_username: fontuni

# Build settings
markdown: kramdown
exclude: [CNAME, README.md]
timezone: ASIA/BANGKOK
encoding: utf-8
