# Site settings
encoding: utf-8
title: สำนักอักขระฟอนต์อยู่นี่
short_title: ฟอนต์อยู่นี่
tagline: ฟอนต์เกิดใหม่บ้างในบางเวลา ...
description: > # this means to ignore newlines until "baseurl:"
  สำนักอักขระฟอนต์อยู่นี่  เป็นโรงหล่อฟอนต์เสรีที่มุ่งผลิตฟอนต์ไทยให้แสดงผลได้ถูกต้องและดูไม่แย่ เน้นมาตรฐานยูนิโค้ดและโอเพ่นไทป์ เพื่อให้มนุษย์ไทยและมนุษย์โลกมีอิสระที่จะนำฟอนต์ไปใช้งาน, แจกจ่าย หรือดัดแปลงได้อย่างสบายใจ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fontuni.com" # the base hostname & protocol for your site
timezone: Asia/Bangkok

email: uni@fontuni.com
twitter_username: fontuni
github_username: fontuni

# Build settings
permalink: /articles/:year-:month-:day-:title.html
markdown: kramdown
exclude: [CNAME, README.md]

# Github
github:
  owner_name: "fontuni"
  owner_url: "https://github.com/fontuni"
  repository_url: "https://github.com/fontuni/fontuni.github.io"

collections:
  boon:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
  boonjot:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
  boontook:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
  boonbaan:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
  vain:
    output: true
    defaults:
      scope:
        path: ""
        type: font
        values:
        layout: font
